# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed999b3d2d75dad147aca8d03efd82e1514a1948c9c2be6519cbeb3e643e9206de9fbbbf3ecc7d710bc67c5b17079890b96046acffb5a4579662d8478a29b2ab

test:
  secret_key_base: 76ec50317e8b6cd7553a74900b9f55385e71d5490333f249b8992eda67ab241c6d06066f18a218c97b98be9ed98509acefb9e34f690525823f093652ed9b86ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
